; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
platform = espressif32
board = nodemcu-32s
upload_speed = 921600
monitor_speed = 115200
build_src_filter =
    -<**/*.cpp>

[env:CANreceiverDev]
build_src_filter =
    +<CANbus/receiver_refactor.cpp>
lib_deps =
    https://github.com/sandeepmistry/arduino-CAN

[env:Hub]
platform = ststm32
board = portenta_h7_m7
upload_protocol = udf
build_src_filter =
    +<hub.cpp>
lib_deps =
    arduino-libraries/ArduinoBLE@^1.2.1
    knolleary/PubSubClient@^2.8
    https://github.com/sandeepmistry/arduino-CAN

;sensor env's
[env:BLE]
build_src_filter =
    +<BLESensor.cpp>
lib_deps =
    arduino-libraries/ArduinoBLE@^1.2.1
    adafruit/Adafruit BMP280 Library@^2.6.8

[env:WiFi]
build_src_filter =
    +<WiFiSensor.cpp>
lib_deps =
    arduino-libraries/Arduino_NiclaSenseEnv@^1.0.0

[env:CAN]
build_src_filter =
    +<CANSensor.cpp>
lib_deps =
    https://github.com/sandeepmistry/arduino-CAN




