import json
import matplotlib.pyplot as plt
import numpy as np

def analyze_and_visualize_survey_data(json_data_string):
    """
    Analyzes survey data from a JSON string and visualizes the average ratings.

    Args:
        json_data_string (str): A string containing a JSON array of survey responses.
                                Each response should be in the format generated by the HTML questionnaire.
    """
    try:
        # Load the JSON data
        # Assumes json_data_string is a JSON array of survey submissions.
        # Example: '[{"timestamp": "...", "userId": "...", "feedback": {...}}, {"timestamp": "...", "userId": "...", "feedback": {...}}]'
        all_responses = json.loads(json_data_string)
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        print("Please ensure your JSON data is correctly formatted as a list of survey responses.")
        return

    if not all_responses:
        print("No survey responses found in the provided JSON data. Cannot create a visualization.")
        return

    print(f"Loaded {len(all_responses)} survey responses.")

    # Define all questions and their corresponding labels for the chart
    # These labels match the 'label' property in the JavaScript `questions` array.
    questions = [
        {"id": "q1_1", "label": "1.1 Easy to navigate"},
        {"id": "q1_2", "label": "1.2 Multi-device seamless"},
        {"id": "q1_3", "label": "1.3 Loading time acceptable"},
        {"id": "q2_1", "label": "2.1 Data presented clearly"},
        {"id": "q2_2", "label": "2.2 Easy to identify anomalies"},
        {"id": "q2_3", "label": "2.3 Hub distinction clear"},
        {"id": "q2_4", "label": "2.4 Historical data useful"},
        {"id": "q3_1", "label": "3.1 Centralized view improves efficiency"},
        {"id": "q3_2", "label": "3.2 Data is up-to-date"},
        {"id": "q3_3", "label": "3.3 Reduces issue identification time"},
        {"id": "q4_1", "label": "4.1 Aids energy transition"},
        {"id": "q4_2", "label": "4.2 Helps network stability"},
        {"id": "q4_3", "label": "4.3 Enhances network efficiency"}
    ]

    # Initialize a dictionary to store total scores for each question
    total_scores = {q["id"]: 0 for q in questions}

    # Aggregate scores from all responses
    for response in all_responses:
        feedback = response.get("feedback", {}) # Use .get() for safe access
        
        # Access nested sections safely
        overall_usability = feedback.get("overallUsability", {})
        data_visualization = feedback.get("dataVisualization", {})
        functionality_efficiency = feedback.get("functionalityEfficiency", {})
        relevance_to_stedin_goals = feedback.get("relevanceToStedinGoals", {})

        # Sum up scores for each question, using .get() with a default of 0
        total_scores["q1_1"] += overall_usability.get("q1_1", 0)
        total_scores["q1_2"] += overall_usability.get("q1_2", 0)
        total_scores["q1_3"] += overall_usability.get("q1_3", 0)

        total_scores["q2_1"] += data_visualization.get("q2_1", 0)
        total_scores["q2_2"] += data_visualization.get("q2_2", 0)
        total_scores["q2_3"] += data_visualization.get("q2_3", 0)
        total_scores["q2_4"] += data_visualization.get("q2_4", 0)

        total_scores["q3_1"] += functionality_efficiency.get("q3_1", 0)
        total_scores["q3_2"] += functionality_efficiency.get("q3_2", 0)
        total_scores["q3_3"] += functionality_efficiency.get("q3_3", 0)

        total_scores["q4_1"] += relevance_to_stedin_goals.get("q4_1", 0)
        total_scores["q4_2"] += relevance_to_stedin_goals.get("q4_2", 0)
        total_scores["q4_3"] += relevance_to_stedin_goals.get("q4_3", 0)

    # Calculate average scores
    num_responses = len(all_responses)
    average_scores = [total_scores[q["id"]] / num_responses for q in questions]

    # Prepare data for plotting
    question_labels = [q["label"] for q in questions]
    x_pos = np.arange(len(question_labels)) # Position for bars on x-axis

    # Create the bar chart
    plt.figure(figsize=(12, 7)) # Adjust figure size for better readability
    bars = plt.bar(x_pos, average_scores, color='skyblue')
    plt.xlabel('Survey Questions')
    plt.ylabel('Average Rating (1-10)')
    plt.title(f'Average Usability Ratings for Stedin Dashboard ({num_responses} Submissions)')
    plt.xticks(x_pos, question_labels, rotation=45, ha='right') # Rotate labels for readability
    plt.ylim(0, 10) # Set y-axis limit from 0 to 10 for consistency
    plt.grid(axis='y', linestyle='--', alpha=0.7) # Add a horizontal grid for better readability

    # Add labels to the top of the bars
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 0.1, round(yval, 2), ha='center', va='bottom')

    plt.tight_layout() # Adjust layout to prevent labels from overlapping
    plt.show()

# --- How to use this script ---
# 1. Go to your HTML questionnaire (the Canvas).
# 2. Submit a few surveys to collect data.
# 3. Click the "Copy All JSON to Clipboard" button.
# 4. Paste that copied JSON string into the 'your_json_data_here' variable below.
#    Make sure it's enclosed in triple quotes ('''...''').

your_json_data_here = """
[
    {
        "timestamp": "2025-06-08T11:53:56.829Z",
        "userId": "454234",
        "feedback": {
            "overallUsability": {
                "q1_1": 10,
                "q1_2": 7,
                "q1_3": 10
            },
            "dataVisualization": {
                "q2_1": 10,
                "q2_2": 10,
                "q2_3": 10,
                "q2_4": 7
            },
            "functionalityEfficiency": {
                "q3_1": 10,
                "q3_2": 10,
                "q3_3": 5
            },
            "relevanceToStedinGoals": {
                "q4_1": 8,
                "q4_2": 8,
                "q4_3": 7
            },
            "additionalComments": "no export csv button"
        }
    },
    {
        "timestamp": "2025-06-08T12:00:00.000Z",
        "userId": "567890",
        "feedback": {
            "overallUsability": {
                "q1_1": 8,
                "q1_2": 9,
                "q1_3": 9
            },
            "dataVisualization": {
                "q2_1": 9,
                "q2_2": 8,
                "q2_3": 9,
                "q2_4": 8
            },
            "functionalityEfficiency": {
                "q3_1": 9,
                "q3_2": 9,
                "q3_3": 7
            },
            "relevanceToStedinGoals": {
                "q4_1": 9,
                "q4_2": 9,
                "q4_3": 8
            },
            "additionalComments": "Could use more filters"
        }
    },
    {
        "timestamp": "2025-06-08T12:05:30.000Z",
        "userId": "112233",
        "feedback": {
            "overallUsability": {
                "q1_1": 7,
                "q1_2": 6,
                "q1_3": 8
            },
            "dataVisualization": {
                "q2_1": 7,
                "q2_2": 6,
                "q2_3": 7,
                "q2_4": 6
            },
            "functionalityEfficiency": {
                "q3_1": 8,
                "q3_2": 7,
                "q3_3": 6
            },
            "relevanceToStedinGoals": {
                "q4_1": 7,
                "q4_2": 6,
                "q4_3": 6
            },
            "additionalComments": "Some graphs are hard to read on smaller screens."
        }
    },
    {
        "timestamp": "2025-06-08T12:02:07.073Z",
        "userId": "Tibor",
        "feedback": {
            "overallUsability": {
                "q1_1": 9,
                "q1_2": 10,
                "q1_3": 10
            },
            "dataVisualization": {
                "q2_1": 9,
                "q2_2": 8,
                "q2_3": 5,
                "q2_4": 10
            },
            "functionalityEfficiency": {
                "q3_1": 8,
                "q3_2": 10,
                "q3_3": 5
            },
            "relevanceToStedinGoals": {
                "q4_1": 10,
                "q4_2": 5,
                "q4_3": 5
            },
            "additionalComments": ""
        }
    },
    {
        "timestamp": "2025-06-08T11:55:47.307Z",
        "userId": "Femke",
        "feedback": {
            "overallUsability": {
                "q1_1": 8,
                "q1_2": 6,
                "q1_3": 8
            },
            "dataVisualization": {
                "q2_1": 8,
                "q2_2": 7,
                "q2_3": 8,
                "q2_4": 8
            },
            "functionalityEfficiency": {
                "q3_1": 8,
                "q3_2": 8,
                "q3_3": 7
            },
            "relevanceToStedinGoals": {
                "q4_1": 8,
                "q4_2": 8,
                "q4_3": 8
            },
            "additionalComments": ""
        }
    }
]
"""

# Call the function with your JSON data
analyze_and_visualize_survey_data(your_json_data_here)

