
version: '3'
services:
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html
    networks:
      - app-network

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/password_file:/mosquitto/config/password_file
      - ./mosquitto/acl_file:/mosquitto/config/acl_file
      - ./ssl:/mosquitto/ssl
    ports:
      - "1883:1883"  
      - "1884:1884"  
    networks:
      - app-network
      

networks:
  app-network:
    driver: bridge